// olea-contracts public entry point.
//
// INV-1: this package (and every file under it) MUST NEVER import `obsidian`.
// See scripts/check-inv1.mjs and packages/core/test/inv1.probe.spec.ts.

// The versioned-artifact envelope (BND-3) — the one shape every delivered
// result travels inside: version stamp, cache lifetime, evidentiary basis, and
// an explicit statement of what must never ride in it. The study plan and the
// two delivered thresholds the component register names are expressed against
// it here.
export {
  ARTIFACT_ENVELOPE_VERSION,
  type ArtifactEnvelopeHeader,
  artifactEnvelope,
  type ClaimBasis,
  claim,
  claimBasis,
  DEPTH_GATE_BODY_VERSION,
  DEPTH_GATE_CONTRACT_ID,
  DEPTH_GATE_ENDPOINT_PATH,
  DEPTH_GATE_KIND,
  type DepthGateBody,
  type DepthGateEnvelope,
  depthGateBody,
  depthGateEnvelope,
  type EnvelopeReadResult,
  type EnvelopeState,
  type EnvelopeUnreadableReason,
  type EvidenceRef,
  envelopeFreshness,
  envelopeState,
  evidenceRef,
  GOVERNING_FRESH_FOR_SECONDS,
  GOVERNING_GOVERNS_FOR_SECONDS,
  MISCONCEPTION_MERGE_BODY_VERSION,
  MISCONCEPTION_MERGE_CONTRACT_ID,
  MISCONCEPTION_MERGE_KIND,
  type MisconceptionMergeBody,
  type MisconceptionMergeEnvelope,
  misconceptionMergeBody,
  misconceptionMergeEnvelope,
  OPERATING_FRESH_FOR_SECONDS,
  OPERATING_GOVERNS_FOR_SECONDS,
  plannedConceptBasis,
  RANK_WEIGHTS_BODY_VERSION,
  RANK_WEIGHTS_CONTRACT_ID,
  RANK_WEIGHTS_ENDPOINT_PATH,
  RANK_WEIGHTS_KIND,
  type RankWeightsBody,
  type RankWeightsEnvelope,
  READABLE_ENVELOPE_VERSIONS,
  rankWeightsBody,
  rankWeightsEnvelope,
  readArtifactEnvelope,
  STUDY_PLAN_BODY_VERSION,
  STUDY_PLAN_ENVELOPE_CONTRACT_ID,
  STUDY_PLAN_KIND,
  type StudyPlanBody,
  type StudyPlanEnvelope,
  studyPlanBody,
  studyPlanEnvelope,
  VISION_ROUTE_BODY_VERSION,
  VISION_ROUTE_CONTRACT_ID,
  VISION_ROUTE_ENDPOINT_PATH,
  VISION_ROUTE_KIND,
  type VisionRouteBody,
  type VisionRouteEnvelope,
  visionRouteBody,
  visionRouteEnvelope,
} from './artifact-envelope.js';
// The per-item citation fragment on `quiz.generate.v1` / `cards.generate.v1` — `[D-446]` option
// (a), the draft-time half (`ol-egov.141.89.2.29`): `groundedIn`, the 0-based positions in the
// request's `sourceChunks` an item rests on, optional and never a reason to fail an item. See the
// module's own header.
export {
  AUTHORING_CITATION_TASK_IDS,
  type AuthoringCitationTaskId,
  type AuthoringGroundedIn,
  authoringGroundedIn,
  authoringGroundedInField,
  readAuthoringGroundedIn,
} from './authoring-citation.js';
// The demand-carriage wire fragment on `quiz.generate.v1` / `cards.generate.v1` — `[D-437]`
// (`ol-egov.141.89.57`), design section 4.3 of `docs/dev/intelligence-build/demand-carriage.md`
// (service repo, cited by path), amended by the 2026-09-29 rulings on rows 35 to 38. The
// vocabulary IS `explainBackJudgeDemand`; what this adds is the served-demand declaration, the
// primary heading ask and the acknowledgement. See the module's own header.
export {
  AUTHORING_DEMAND_TASK_IDS,
  AUTHORING_SERVED_DEMANDS,
  type AuthoringDemand,
  type AuthoringDemandAcknowledgement,
  type AuthoringDemandTaskId,
  type AuthoringRequestedAsk,
  authoringDeclaredDemandField,
  authoringDemand,
  authoringDemandAcknowledgement,
  authoringDemandServed,
  authoringIntendedDemandField,
  authoringRequestedAsk,
  authoringRequestedAskField,
} from './authoring-demand.js';
// `explain-back.judge.v1`'s optional learning-target bundle and its
// response-envelope acknowledgement — `[D-277 / TARGET-1]` (`ol-egov.141.87`),
// landed by TARGET-2 (`ol-0r92.92`). See the module's own header for why this
// one wire fragment is fixed here rather than restated per caller the way the
// rest of this task's request/response shape is.
export {
  EXPLAIN_BACK_JUDGE_TARGET_SCHEMA_VERSION,
  type ExplainBackJudgeAdequacyCriterion,
  type ExplainBackJudgeDemand,
  type ExplainBackJudgeDisqualifier,
  type ExplainBackJudgeLearningTarget,
  type ExplainBackJudgeSpecificationAcknowledgement,
  explainBackJudgeAdequacyCriterion,
  explainBackJudgeDemand,
  explainBackJudgeDisqualifier,
  explainBackJudgeLearningTarget,
  explainBackJudgeLearningTargetField,
  explainBackJudgeSpecificationAcknowledgement,
} from './explain-back-judge-target.js';
export { type ContractEntry, type ContractId, contracts, SchemaRegistry } from './registry.js';

// The D7.1 review-log record and the Worker envelope, re-exported together.
// "Frozen schemas... what two parallel lanes must not move underneath each
// other" used to describe this grouping; that was P3-T01/P3-T02
// lane-coordination, and those lanes forked and finished long ago (ol-jnt0).
// What is actually load-bearing about each export is documented at its own
// definition: review-log.ts's header explains D-020's per-version freeze (a
// shipped version's shape never changes; that is the real, standing rule),
// and worker.ts's header explains D-011's versioning discipline for the
// envelope.
export {
  type AnswerEdits,
  type ArtifactProvenance,
  type ArtifactVerdict,
  answerEdits,
  artifactProvenance,
  artifactVerdict,
  type ContestEffect,
  type ContestedClaimKind,
  type ContestedClaimRendering,
  contestEffect,
  contestedClaimKind,
  contestedClaimRendering,
  type DisputeLogRecord,
  type DisputeLogRecordV5,
  type DisputeLogRecordV6,
  disputeLogRecord,
  disputeLogRecordV5,
  disputeLogRecordV6,
  type ExplainBackCorrectness,
  type ExplainBackCorrectnessReading,
  type ExplainBackCorrectnessVerdict,
  type ExplainBackDeclineManner,
  type ExplainBackFeedbackShownLogRecord,
  type ExplainBackFeedbackShownLogRecordV6,
  type ExplainBackGrade,
  type ExplainBackGradingProvenance,
  type ExplainBackOfferEventKind,
  type ExplainBackOfferLogRecord,
  type ExplainBackOfferLogRecordV5,
  type ExplainBackOfferLogRecordV6,
  type ExplainBackOfferTrigger,
  type ExplainBackRestatementFinding,
  type ExplainBackSetAsideLogRecord,
  type ExplainBackSetAsideLogRecordV6,
  type ExplainBackSetAsideOutcome,
  explainBackCorrectness,
  explainBackCorrectnessVerdict,
  explainBackDeclineManner,
  explainBackFeedbackShownLogRecord,
  explainBackFeedbackShownLogRecordV6,
  explainBackGrade,
  explainBackGradingProvenance,
  explainBackOfferEventKind,
  explainBackOfferLogRecord,
  explainBackOfferLogRecordV5,
  explainBackOfferLogRecordV6,
  explainBackOfferTrigger,
  explainBackRestatementFinding,
  explainBackSetAsideLogRecord,
  explainBackSetAsideLogRecordV6,
  explainBackSetAsideOutcome,
  type InstrumentType,
  instrumentType,
  type MasteryAtTime,
  type MasteryAtTimeV6,
  type MasteryState,
  type McqCorrectness,
  type McqMisconceptionProvenance,
  type MisconceptionObservedLogRecord,
  type MisconceptionObservedLogRecordV5,
  type MisconceptionObservedLogRecordV6,
  masteryAtTime,
  masteryAtTimeV6,
  masteryState,
  mcqCorrectness,
  mcqMisconceptionProvenance,
  misconceptionObservedLogRecord,
  misconceptionObservedLogRecordV5,
  misconceptionObservedLogRecordV6,
  type NonAttemptLogRecord,
  type NonAttemptLogRecordV5,
  type NonAttemptLogRecordV6,
  nonAttemptLogRecord,
  nonAttemptLogRecordV5,
  nonAttemptLogRecordV6,
  type Rating,
  REVIEW_LOG_READABLE_VERSIONS,
  REVIEW_LOG_SCHEMA_VERSION,
  type RetrospectiveOfferEventKind,
  type RetrospectiveOfferLogRecord,
  type RetrospectiveOfferLogRecordV5,
  type RetrospectiveOfferLogRecordV6,
  type ReviewLogEntry,
  type ReviewLogEntryV2,
  type ReviewLogEntryV3,
  type ReviewLogEntryV5,
  type ReviewLogEntryV6,
  type ReviewLogRecord,
  type ReviewLogRecordV1,
  type ReviewLogRecordV2,
  type ReviewLogRecordV3,
  type ReviewLogRecordV5,
  type ReviewLogRecordV6,
  rating,
  readExplainBackCorrectness,
  restatementFindingOf,
  retrospectiveOfferEventKind,
  retrospectiveOfferLogRecord,
  retrospectiveOfferLogRecordV5,
  retrospectiveOfferLogRecordV6,
  reviewLogEntry,
  reviewLogEntryV2,
  reviewLogEntryV3,
  reviewLogEntryV5,
  reviewLogEntryV6,
  reviewLogRecord,
  reviewLogRecordV1,
  reviewLogRecordV2,
  reviewLogRecordV3,
  reviewLogRecordV5,
  reviewLogRecordV6,
  type SchedulingObservation,
  type SelectionContext,
  type SelectionContextV4,
  type SoloLevel,
  type SourceRegisteredLogRecord,
  type SourceRegisteredLogRecordV5,
  type SourceRegisteredLogRecordV6,
  type SourceRegisteredRole,
  type SuccessionLogRecord,
  type SuccessionLogRecordV5,
  type SuccessionLogRecordV6,
  type SupportLevel,
  type SuspendEventKind,
  type SuspendLogRecord,
  type SuspendLogRecordV2,
  type SuspendLogRecordV3,
  type SuspendLogRecordV5,
  type SuspendLogRecordV6,
  type SuspensionReason,
  schedulingObservation,
  selectionContext,
  selectionContextV4,
  soloLevel,
  sourceRegisteredLogRecord,
  sourceRegisteredLogRecordV5,
  sourceRegisteredLogRecordV6,
  sourceRegisteredRole,
  successionLogRecord,
  successionLogRecordV5,
  successionLogRecordV6,
  supportLevel,
  suspendEventKind,
  suspendLogRecord,
  suspendLogRecordV2,
  suspendLogRecordV3,
  suspendLogRecordV5,
  suspendLogRecordV6,
  suspensionReason,
  type VerdictLogRecord,
  type VerdictLogRecordV5,
  type VerdictLogRecordV6,
  type VitalityValue,
  verdictLogRecord,
  verdictLogRecordV5,
  verdictLogRecordV6,
  vitalityValue,
} from './review-log.js';
// The versioned study-plan artifact (A2.5, C7.6, P5-T05). Worker-computed
// policy, cached and executed client-side; its `planVersion` is the one value
// that crosses from here into her append-only review log.
export {
  type EmptyRankingReason,
  emptyRankingReason,
  type PlannedConcept,
  plannedConcept,
  STUDY_PLAN_CONTRACT_ID,
  STUDY_PLAN_FORMAT_VERSION,
  type StudyPlanAllocationEntry,
  type StudyPlanArtifact,
  type StudyPlanCitation,
  type StudyPlanCourse,
  studyPlanAllocationEntry,
  studyPlanArtifact,
  studyPlanCitation,
  studyPlanCourse,
} from './study-plan.js';
export {
  ALL_TASK_IDS,
  isKnownTaskId,
  isValidRemainingAllowanceUsd,
  type KnownTaskId,
  knownTaskId,
  type RemainingAllowanceField,
  refineSourceChunkOriginAlignment,
  SOURCE_CHUNK_ORIGIN_TASK_IDS,
  type SourceChunkOriginTaskId,
  sourceBlockOriginField,
  sourceChunkOriginsField,
  TASK_ENDPOINT_PATH,
  TASK_IDS,
  TRANSCRIPT_SEGMENT_FLAGS,
  TRANSCRIPT_SPEAKER_ROLES,
  type TranscriptSegmentFlag,
  type TranscriptSourceChunkOrigin,
  type TranscriptSpeakerRole,
  transcriptSourceChunkOrigin,
} from './tasks.js';
export {
  CONTRACT_VERSION,
  type ErrorCode,
  type ErrorResponse,
  errorCode,
  errorResponse,
  isSupportedContractVersion,
  type RequestEnvelope,
  type RequestTelemetry,
  type ResponseStamp,
  requestEnvelope,
  requestTelemetry,
  responseStamp,
  SUPPORTED_CONTRACT_VERSIONS,
  type SuccessResponse,
  successResponse,
  type TaskId,
  taskId,
  type UsageBlock,
  type UsageSource,
  usageBlock,
  usageSource,
  type WorkerResponse,
  workerResponse,
} from './worker.js';
