// olea-contracts public entry point.
//
// INV-1: this package (and every file under it) MUST NEVER import `obsidian`.
// See scripts/check-inv1.mjs and packages/core/test/inv1.probe.spec.ts.

// The versioned-artifact envelope (BND-3) — the one shape every delivered
// result travels inside: version stamp, cache lifetime, evidentiary basis, and
// an explicit statement of what must never ride in it. The study plan and the
// two delivered thresholds the component register names are expressed against
// it here.
export {
  ARTIFACT_ENVELOPE_VERSION,
  type ArtifactEnvelopeHeader,
  artifactEnvelope,
  type ClaimBasis,
  claim,
  claimBasis,
  DEPTH_GATE_BODY_VERSION,
  DEPTH_GATE_CONTRACT_ID,
  DEPTH_GATE_ENDPOINT_PATH,
  DEPTH_GATE_KIND,
  type DepthGateBody,
  type DepthGateEnvelope,
  depthGateBody,
  depthGateEnvelope,
  type EnvelopeReadResult,
  type EnvelopeState,
  type EnvelopeUnreadableReason,
  type EvidenceRef,
  envelopeFreshness,
  envelopeState,
  evidenceRef,
  GOVERNING_FRESH_FOR_SECONDS,
  GOVERNING_GOVERNS_FOR_SECONDS,
  MISCONCEPTION_MERGE_BODY_VERSION,
  MISCONCEPTION_MERGE_CONTRACT_ID,
  MISCONCEPTION_MERGE_KIND,
  type MisconceptionMergeBody,
  type MisconceptionMergeEnvelope,
  misconceptionMergeBody,
  misconceptionMergeEnvelope,
  OPERATING_FRESH_FOR_SECONDS,
  OPERATING_GOVERNS_FOR_SECONDS,
  plannedConceptBasis,
  RANK_WEIGHTS_BODY_VERSION,
  RANK_WEIGHTS_CONTRACT_ID,
  RANK_WEIGHTS_ENDPOINT_PATH,
  RANK_WEIGHTS_KIND,
  type RankWeightsBody,
  type RankWeightsEnvelope,
  READABLE_ENVELOPE_VERSIONS,
  rankWeightsBody,
  rankWeightsEnvelope,
  readArtifactEnvelope,
  STUDY_PLAN_BODY_VERSION,
  STUDY_PLAN_ENVELOPE_CONTRACT_ID,
  STUDY_PLAN_KIND,
  type StudyPlanBody,
  type StudyPlanEnvelope,
  studyPlanBody,
  studyPlanEnvelope,
  VISION_ROUTE_BODY_VERSION,
  VISION_ROUTE_CONTRACT_ID,
  VISION_ROUTE_ENDPOINT_PATH,
  VISION_ROUTE_KIND,
  type VisionRouteBody,
  type VisionRouteEnvelope,
  visionRouteBody,
  visionRouteEnvelope,
} from './artifact-envelope.js';
// `explain-back.judge.v1`'s optional learning-target bundle and its
// response-envelope acknowledgement — `[D-277 / TARGET-1]` (`ol-egov.141.87`),
// landed by TARGET-2 (`ol-0r92.92`). See the module's own header for why this
// one wire fragment is fixed here rather than restated per caller the way the
// rest of this task's request/response shape is.
export {
  EXPLAIN_BACK_JUDGE_TARGET_SCHEMA_VERSION,
  type ExplainBackJudgeAdequacyCriterion,
  type ExplainBackJudgeDemand,
  type ExplainBackJudgeDisqualifier,
  type ExplainBackJudgeLearningTarget,
  type ExplainBackJudgeSpecificationAcknowledgement,
  explainBackJudgeAdequacyCriterion,
  explainBackJudgeDemand,
  explainBackJudgeDisqualifier,
  explainBackJudgeLearningTarget,
  explainBackJudgeLearningTargetField,
  explainBackJudgeSpecificationAcknowledgement,
} from './explain-back-judge-target.js';
export { type ContractEntry, type ContractId, contracts, SchemaRegistry } from './registry.js';

// The D7.1 review-log record and the Worker envelope, re-exported together.
// "Frozen schemas... what two parallel lanes must not move underneath each
// other" used to describe this grouping; that was P3-T01/P3-T02
// lane-coordination, and those lanes forked and finished long ago (ol-jnt0).
// What is actually load-bearing about each export is documented at its own
// definition: review-log.ts's header explains D-020's per-version freeze (a
// shipped version's shape never changes; that is the real, standing rule),
// and worker.ts's header explains D-011's versioning discipline for the
// envelope.
export {
  type AnswerEdits,
  type ArtifactProvenance,
  type ArtifactVerdict,
  answerEdits,
  artifactProvenance,
  artifactVerdict,
  type ContestEffect,
  type ContestedClaimKind,
  type ContestedClaimRendering,
  contestEffect,
  contestedClaimKind,
  contestedClaimRendering,
  type DisputeLogRecord,
  type DisputeLogRecordV5,
  disputeLogRecord,
  disputeLogRecordV5,
  type ExplainBackDeclineManner,
  type ExplainBackGrade,
  type ExplainBackOfferEventKind,
  type ExplainBackOfferLogRecord,
  type ExplainBackOfferLogRecordV5,
  type ExplainBackOfferTrigger,
  explainBackDeclineManner,
  explainBackGrade,
  explainBackOfferEventKind,
  explainBackOfferLogRecord,
  explainBackOfferLogRecordV5,
  explainBackOfferTrigger,
  type InstrumentType,
  instrumentType,
  type MasteryAtTime,
  type MasteryState,
  type McqCorrectness,
  type McqMisconceptionProvenance,
  type MisconceptionObservedLogRecord,
  type MisconceptionObservedLogRecordV5,
  masteryAtTime,
  masteryState,
  mcqCorrectness,
  mcqMisconceptionProvenance,
  misconceptionObservedLogRecord,
  misconceptionObservedLogRecordV5,
  type NonAttemptLogRecord,
  type NonAttemptLogRecordV5,
  nonAttemptLogRecord,
  nonAttemptLogRecordV5,
  type Rating,
  REVIEW_LOG_READABLE_VERSIONS,
  REVIEW_LOG_SCHEMA_VERSION,
  type RetrospectiveOfferEventKind,
  type RetrospectiveOfferLogRecord,
  type RetrospectiveOfferLogRecordV5,
  type ReviewLogEntry,
  type ReviewLogEntryV2,
  type ReviewLogEntryV3,
  type ReviewLogEntryV5,
  type ReviewLogRecord,
  type ReviewLogRecordV1,
  type ReviewLogRecordV2,
  type ReviewLogRecordV3,
  type ReviewLogRecordV5,
  rating,
  retrospectiveOfferEventKind,
  retrospectiveOfferLogRecord,
  retrospectiveOfferLogRecordV5,
  reviewLogEntry,
  reviewLogEntryV2,
  reviewLogEntryV3,
  reviewLogEntryV5,
  reviewLogRecord,
  reviewLogRecordV1,
  reviewLogRecordV2,
  reviewLogRecordV3,
  reviewLogRecordV5,
  type SchedulingObservation,
  type SelectionContext,
  type SelectionContextV4,
  type SoloLevel,
  type SourceRegisteredLogRecord,
  type SourceRegisteredLogRecordV5,
  type SourceRegisteredRole,
  type SuccessionLogRecord,
  type SuccessionLogRecordV5,
  type SupportLevel,
  type SuspendEventKind,
  type SuspendLogRecord,
  type SuspendLogRecordV2,
  type SuspendLogRecordV3,
  type SuspendLogRecordV5,
  schedulingObservation,
  selectionContext,
  selectionContextV4,
  soloLevel,
  sourceRegisteredLogRecord,
  sourceRegisteredLogRecordV5,
  sourceRegisteredRole,
  successionLogRecord,
  successionLogRecordV5,
  supportLevel,
  suspendEventKind,
  suspendLogRecord,
  suspendLogRecordV2,
  suspendLogRecordV3,
  suspendLogRecordV5,
  type VerdictLogRecord,
  type VerdictLogRecordV5,
  verdictLogRecord,
  verdictLogRecordV5,
} from './review-log.js';
// The versioned study-plan artifact (A2.5, C7.6, P5-T05). Worker-computed
// policy, cached and executed client-side; its `planVersion` is the one value
// that crosses from here into her append-only review log.
export {
  type PlannedConcept,
  plannedConcept,
  STUDY_PLAN_CONTRACT_ID,
  STUDY_PLAN_FORMAT_VERSION,
  type StudyPlanAllocationEntry,
  type StudyPlanArtifact,
  type StudyPlanCitation,
  type StudyPlanCourse,
  studyPlanAllocationEntry,
  studyPlanArtifact,
  studyPlanCitation,
  studyPlanCourse,
} from './study-plan.js';
export {
  ALL_TASK_IDS,
  isKnownTaskId,
  type KnownTaskId,
  knownTaskId,
  TASK_ENDPOINT_PATH,
  TASK_IDS,
} from './tasks.js';
export {
  CONTRACT_VERSION,
  type ErrorCode,
  type ErrorResponse,
  errorCode,
  errorResponse,
  isSupportedContractVersion,
  type RequestEnvelope,
  type RequestTelemetry,
  type ResponseStamp,
  requestEnvelope,
  requestTelemetry,
  responseStamp,
  SUPPORTED_CONTRACT_VERSIONS,
  type SuccessResponse,
  successResponse,
  type TaskId,
  taskId,
  type UsageBlock,
  type UsageSource,
  usageBlock,
  usageSource,
  type WorkerResponse,
  workerResponse,
} from './worker.js';
