import { builtinModules } from 'node:module';
import process from 'node:process';
import esbuild from 'esbuild';

// Hoisted from the official obsidian-sample-plugin esbuild config
// (community-tested path for the plugin bundle — plan §1.2). `obsidian` and
// friends are externalized because Obsidian provides them at runtime; they
// are never bundled into main.js.
//
// `builtinModules` (from `node:module`) lists bare specifiers ("fs", "path",
// ...), never the `node:`-prefixed form — Node itself resolves both, but
// esbuild's `external` matching is exact-string, so listing only the bare
// names leaves every `import ... from 'node:fs'` unmatched and esbuild
// tries to actually bundle it (and fails: there's no such file on disk
// outside a real Node resolver). This was latent as long as nothing in the
// plugin bundle transitively reached a `node:`-prefixed import; `olea-core`
// exports `FolderSource` (`node:fs`/`node:path`, test/CLI-only, never
// exercised inside Obsidian) from the same barrel `packages/plugin` now
// pulls real runtime values from (P3-T03a's `ingestion/wiring.ts`), so it
// surfaced here. Obsidian's desktop host is Electron with Node integration,
// so externalizing (not bundling) these is correct either way — identical
// to how `obsidian`/`electron` themselves are handled below.
const NODE_BUILTINS_BOTH_FORMS = builtinModules.flatMap((name) => [name, `node:${name}`]);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, see https://github.com/OlvaroAB/olea (packages/plugin)
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...NODE_BUILTINS_BOTH_FORMS,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
