/**
 * F9.S5 — "Goldens per persona per week, and the manual set untouched"
 * (`features/F9-simulator.md`, `@auto-web:simulator/goldens`,
 * `docs/dev/simulator-design.md` §6).
 *
 * One independent `test()` per (week × surface) — same convention
 * `visual-regression.spec.ts` uses (a fresh, addressable page load per
 * screenshot rather than one long stateful walk), adapted to the simulator's
 * one-route reality by having each test do its own reset-then-advance from
 * scratch. `week * 7` days from a shared, fixed reset point (rather than
 * chaining N sequential tests) is what makes every test independent AND
 * still "N weeks of the same lived term" — a week-3 test starting from a
 * fresh reset and advancing 21 days lands on exactly the same simulated date
 * a week-0→1→2→3 walk would, because nothing here is randomised and no test
 * ever presses `[data-sim-rate]` (a golden of what a day with no session
 * looks like, matching F9.S2's own "never fabricates behaviour" claim).
 *
 * KEYING (F9.S5's own acceptance line): `toHaveScreenshot` takes an ARRAY —
 * `[world, persona, '<week>--<surface>.png']` — and `playwright.config.ts`'s
 * `simulator` project sets `snapshotPathTemplate` to join that array as
 * literal path segments under `e2e/simulator/__screenshots__/`, so the golden
 * on disk really is `simulator/<world>/<persona>/<week>--<surface>.png`
 * (relative to `e2e/`) with no project/platform suffix — adding a second
 * `persona` value only ever adds new files under a new `<persona>/`
 * directory; it can never touch an existing one, because no golden's
 * filename or path segment depends on any OTHER persona's identity.
 *
 * WORLD/GOLDENS ARE ENV-PARAMETERISABLE, NOT YET WORLD-AWARE: `WB_SIM_WORLD`
 * (default `'fixture'`) only changes the FIRST path segment and the `?world=`
 * query param this suite passes — `SimulatorController` (`ol-3ux7.64.10`
 * [WBX-1b]) does not yet read that param and always mounts the fixture
 * vault (§7 of the design doc is designed, not built). Real-world goldens
 * are NOT generated by this file today; it is shaped so that WBX-6/7's
 * private serve can later run this exact spec with `WB_SIM_WORLD=real
 * WB_SIM_GOLDENS=<absolute path>/.olea-simulator/goldens pnpm exec
 * playwright test --project=simulator` against a build that DOES read the
 * param, with zero spec changes — see `playwright.config.ts`'s
 * `SIM_GOLDENS_DIR`. `WB_SIM_GOLDENS` is never read directly by this file;
 * it is read once, by the config, before any test runs.
 *
 * PERSONA: held at `'none'` for the same reason `visual-regression.spec.ts`
 * holds persona at `'none'` — it is an independent axis this bead's own
 * acceptance criterion (world × persona × week × surface KEYING) does not
 * require enumerating today, and `SimulatorController` has no persona
 * switch yet regardless (see above).
 */
import { expect, test } from '@playwright/test';
import { hostFrameElement } from '../helpers.js';
import {
  advanceDays,
  COMMAND_SESSION_BUILD,
  COMMAND_TODAY_OPEN,
  gotoSimulator,
  openCommandViaPalette,
  resetSimulator,
  VIEW_TYPE_SESSION_BUILDER,
  VIEW_TYPE_TODAY,
} from './helpers.js';

test.describe.configure({ mode: 'parallel' });

const WORLD = process.env.WB_SIM_WORLD ?? 'fixture';
const PERSONA = 'none';
const WEEKS = [0, 1, 2, 3] as const;

const SURFACES = {
  today: { commandId: COMMAND_TODAY_OPEN, viewType: VIEW_TYPE_TODAY },
  session: { commandId: COMMAND_SESSION_BUILD, viewType: VIEW_TYPE_SESSION_BUILDER },
} as const;

for (const week of WEEKS) {
  for (const [surface, { commandId, viewType }] of Object.entries(SURFACES)) {
    test(`@auto-web:simulator/goldens simulator/${WORLD}/${PERSONA}/${week}--${surface}`, async ({
      page,
    }) => {
      await gotoSimulator(page, { world: WORLD, persona: PERSONA });
      await resetSimulator(page);
      if (week > 0) await advanceDays(page, week * 7);
      await openCommandViaPalette(page, commandId, viewType);
      await expect(hostFrameElement(page)).toHaveScreenshot([
        WORLD,
        PERSONA,
        `${week}--${surface}.png`,
      ]);
    });
  }
}
